//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class BuildinObject
{
    public BuildinObject()
    {
        this.InboxDocuments = new HashSet<InboxDocument>();
        this.OutboxDocuments = new HashSet<OutboxDocument>();
    }

    public int Id { get; set; }
    public string ObjName { get; set; }
    public string ObjCode { get; set; }
    public string ProjCypher { get; set; }
    public string SZS { get; set; }

    public virtual ICollection<InboxDocument> InboxDocuments { get; set; }
    public virtual ICollection<OutboxDocument> OutboxDocuments { get; set; }
}
