//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class CompanyStructure
{
    public CompanyStructure()
    {
        this.ChildNodes = new HashSet<CompanyStructure>();
        this.Employes = new HashSet<Employe>();
    }

    public int Id { get; set; }
    public string DepartmentName { get; set; }
    public Nullable<int> ParentDepartmentId { get; set; }

    public virtual ICollection<CompanyStructure> ChildNodes { get; set; }
    public virtual CompanyStructure ParentNode { get; set; }
    public virtual ICollection<Employe> Employes { get; set; }
}
