//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ContractorEmploye
{
    public ContractorEmploye()
    {
        this.InboxDocuments = new HashSet<InboxDocument>();
        this.OutboxDocuments = new HashSet<OutboxDocument>();
    }

    public int Id { get; set; }
    public string FullName { get; set; }
    public string FName { get; set; }
    public string SName { get; set; }
    public string LName { get; set; }
    public string LNameDateln { get; set; }
    public string Post { get; set; }
    public string PostDateln { get; set; }
    public string Gender { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }
    public Nullable<int> Contractor { get; set; }

    public virtual Contractor Contractor1 { get; set; }
    public virtual ICollection<InboxDocument> InboxDocuments { get; set; }
    public virtual ICollection<OutboxDocument> OutboxDocuments { get; set; }
}
