//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Employe
{
    public Employe()
    {
        this.InboxDocuments = new HashSet<InboxDocument>();
        this.OutboxDocuments = new HashSet<OutboxDocument>();
        this.OutboxDocuments1 = new HashSet<OutboxDocument>();
        this.Users = new HashSet<User>();
    }

    public int Id { get; set; }
    public string FullName { get; set; }
    public string NameInDocs { get; set; }
    public string FName { get; set; }
    public string SName { get; set; }
    public string LName { get; set; }
    public string State { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }
    public string Post { get; set; }
    public int DepartmentId { get; set; }

    public virtual ICollection<InboxDocument> InboxDocuments { get; set; }
    public virtual ICollection<OutboxDocument> OutboxDocuments { get; set; }
    public virtual ICollection<OutboxDocument> OutboxDocuments1 { get; set; }
    public virtual ICollection<User> Users { get; set; }
    public virtual CompanyStructure CompanyStructure { get; set; }
}
