//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class FileMetaData
{
    public FileMetaData()
    {
        this.InboxDocuments = new HashSet<InboxDocument>();
        this.OutboxDocuments = new HashSet<OutboxDocument>();
    }

    public int Id { get; set; }
    public string FileName { get; set; }
    public System.DateTime UploadDataTime { get; set; }
    public int Users { get; set; }
    public string FileSize { get; set; }
    public byte[] Data { get; set; }

    public virtual ICollection<InboxDocument> InboxDocuments { get; set; }
    public virtual ICollection<OutboxDocument> OutboxDocuments { get; set; }
}
