//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class InboxDocument
{
    public InboxDocument()
    {
        this.OutboxDocuments = new HashSet<OutboxDocument>();
    }

    public int Id { get; set; }
    public int Sender { get; set; }
    public string SenderNum { get; set; }
    public System.DateTime SenderDate { get; set; }
    public Nullable<int> ResponseOn { get; set; }
    public int Reciever { get; set; }
    public string DocTheme { get; set; }
    public Nullable<int> DocState { get; set; }
    public Nullable<int> BuildingObj { get; set; }
    public Nullable<int> Files { get; set; }

    public virtual BuildinObject BuildinObject { get; set; }
    public virtual ContractorEmploye ContractorEmploye { get; set; }
    public virtual Employe Employe { get; set; }
    public virtual FileMetaData FileMetaData { get; set; }
    public virtual OutboxDocument OutboxDocument { get; set; }
    public virtual ICollection<OutboxDocument> OutboxDocuments { get; set; }
}
