//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class okimtsDbEntities : DbContext
    {
        public okimtsDbEntities()
            : base("name=okimtsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuildinObject> BuildinObjects { get; set; }
        public virtual DbSet<ContractorEmploye> ContractorEmployes { get; set; }
        public virtual DbSet<Contractor> Contractors { get; set; }
        public virtual DbSet<DocState> DocStates { get; set; }
        public virtual DbSet<Employe> Employes { get; set; }
        public virtual DbSet<FileMetaData> FileMetaDatas { get; set; }
        public virtual DbSet<InboxDocument> InboxDocuments { get; set; }
        public virtual DbSet<OutboxDocument> OutboxDocuments { get; set; }
        public virtual DbSet<TypesOfOutboxDoc> TypesOfOutboxDocs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<CompanyStructure> CompanyStructures { get; set; }
    }
}
