//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class OutboxDocument
{
    public OutboxDocument()
    {
        this.InboxDocuments = new HashSet<InboxDocument>();
    }

    public int Id { get; set; }
    public int RecieverOrg { get; set; }
    public Nullable<int> RecieverEmploye { get; set; }
    public Nullable<int> BuildingObj { get; set; }
    public string OutboxNum { get; set; }
    public Nullable<System.DateTime> OutboxDate { get; set; }
    public string DocTheme { get; set; }
    public int WhoSign { get; set; }
    public int WhoMade { get; set; }
    public Nullable<int> ResponseOn { get; set; }
    public Nullable<System.DateTime> SentDate { get; set; }
    public Nullable<int> DocState { get; set; }
    public Nullable<int> Files { get; set; }
    public int TypeOfOutboxDoc { get; set; }
    public Nullable<int> IndexNumber { get; set; }

    public virtual BuildinObject BuildinObject { get; set; }
    public virtual ContractorEmploye ContractorEmploye { get; set; }
    public virtual Contractor Contractor { get; set; }
    public virtual DocState DocState1 { get; set; }
    public virtual Employe Employe { get; set; }
    public virtual Employe Employe1 { get; set; }
    public virtual FileMetaData FileMetaData { get; set; }
    public virtual ICollection<InboxDocument> InboxDocuments { get; set; }
    public virtual InboxDocument InboxDocument { get; set; }
    public virtual TypesOfOutboxDoc TypesOfOutboxDoc { get; set; }
}
