//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class TypesOfOutboxDoc
{
    public TypesOfOutboxDoc()
    {
        this.OutboxDocuments = new HashSet<OutboxDocument>();
    }

    public int Id { get; set; }
    public string NameOfType { get; set; }
    public string NumberingMethod { get; set; }
    public string NumeratorPrefix { get; set; }

    public virtual ICollection<OutboxDocument> OutboxDocuments { get; set; }
}
