//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class User
{
    public int id { get; set; }
    public System.Guid UniqId { get; set; }
    public string Name { get; set; }
    public int Employe { get; set; }
    public Nullable<bool> Invalid { get; set; }
    public Nullable<int> Files { get; set; }

    public virtual Employe Employe1 { get; set; }
}
